# /etc/nixos/hardware-configuration.nix
#
# Do not modify this file! It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations. Please make changes
# to /etc/nixos/configuration.nix instead.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ # This imports non-detected hardware modules, a safe default.
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # --- Kernel & Boot ---
  # Essential kernel modules needed in the initial RAM disk (initrd) to boot the system.
  # These are critical for accessing your root filesystem.
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ]; # You can force modules to load here if needed.
  boot.kernelModules = [ "kvm-amd" ]; # Extra kernel modules loaded after boot, here for virtualization.
  boot.extraModulePackages = [ ];

  # --- Filesystem Mounting ---
  # This section declaratively defines your system's mount points.
  # NixOS will ensure these are mounted at boot.
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2ccedbb8-49a8-4e77-85c2-b84b9fa2e079";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E20F-2A20";
      fsType = "vfat";
      # Options to ensure correct permissions on the FAT32 boot partition.
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # --- Swap Device ---
  # Activates the specified partition as a swap device.
  swapDevices =
    [ { device = "/dev/disk/by-uuid/deeba16f-dc62-4b19-9098-ad008fdc2a1d"; }
    ];

  # --- Networking Defaults ---
  # A sane default that enables DHCP on network interfaces.
  # This can be overridden by more specific network configurations.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp101s0f3u2c2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  # --- Platform & Microcode ---
  # Defines the host platform architecture and enables automatic microcode updates for your CPU.
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}