# Do not modify this file!  It was generated by 'nixos-generate-config'
# Disk layout (fileSystems + swapDevices) is managed by disko — see disk.nix.
{
  config,
  lib,
  ...
} @ args:
if !(args ? modulesPath)
then {}
else {
  imports = [(args.modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  # Enables DHCP on each ethernet and wireless interface.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  fileSystems."/" = {
    device = lib.mkForce "/dev/disk/by-uuid/7b178d85-e28e-422a-88e1-2418381deb12";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = lib.mkForce "/dev/disk/by-uuid/0A29-E24B";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [
    { device = lib.mkForce "/dev/disk/by-uuid/a7543bdf-d509-4685-9ab1-2d83c3e5fca9"; }
  ];
}
