[global]
    monitor = 0
    font = JetBrainsMono Nerd Font 10
    format = "<b>%s</b>\n%b"
    newest_on_top = true
    width = 350
    height = 100
    origin = top-right
    offset = 20x50
    frame_width = @borderWidth@
    frame_color = @surface1@
    separator_color = @surface1@
    border_radius = @borderRadius_island@
    padding = 12
    horizontal_padding = 16

[urgency_low]
    background = @base@
    foreground = @text@
    timeout = 5

[urgency_normal]
    background = @base@
    foreground = @text@
    timeout = 10

[urgency_critical]
    background = @base@
    foreground = @text@
    frame_color = @red@
    timeout = 20
