[mgr]
show_hidden = true

[opener]
edit = [{ run = 'hx "$@"', block = true }]

[open]
rules = [
  { mime = "text/*",        use = "edit" },
  { mime = "inode/x-empty", use = "edit" },
  { url  = "*",             use = "edit" },
]

[plugin]
prepend_previewers = [
  { url = "*.surql",     run = "bat" },
  { url = "*.surrealql", run = "bat" },
  { url = "*.hurl",      run = "bat" },
]
